INSERT INTO BOOKS (ID, AUTHOR, ISBN,PUBLISH_DATE,TITLE) VALUES(1, 'TEST AUTHOR', 'TESTISBN1', '2023-01-09', 'TEST KITAP 1');
INSERT INTO BOOKS (ID, AUTHOR, ISBN,PUBLISH_DATE,TITLE) VALUES(2, 'TEST AUTHOR2', 'TESTISBN2', '2023-01-09', 'TEST KITAP 2');
INSERT INTO BOOKS (ID, AUTHOR, ISBN,PUBLISH_DATE,TITLE) VALUES(3, 'TEST AUTHOR3', 'TESTISBN3', '2023-01-09', 'TEST KITAP 3');